// This isolated test server uses PGlite and a synthetic login. No external account or database is modified.
import express from 'express';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { createRequire } from 'node:module';
import { mkdir } from 'node:fs/promises';
import { database } from '../test/support/database.js';
import { RuralRepository } from '../src/rural/repository.js';
import { RuralService } from '../src/rural/service.js';
import { ruralQuery } from '../src/rural/httpQuery.js';
import { errorHandler } from '../src/middleware/errorHandler.js';
import { agroCatalog } from '../src/rural/agroCatalog.js';

const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
for (const key of ['AGENT_TOOLS_ENABLED', 'AGRO_MODULES_ENABLED', 'EXPENSES_ENABLED', 'INVENTORY_ENABLED']) process.env[key] = 'true';
const { pg, db } = await database();
const repo = new RuralRepository(db);
const user = { id: randomUUID(), email: 'teste@example.test', aud: 'authenticated', app_metadata: {}, user_metadata: {} };
await pg.query('insert into users(id,phone) values($1,$2)', [user.id, '+5511980000010']);
const service = () => new RuralService(user, repo, randomUUID());
const farms = [await service().save('farms', null, { name: 'CT de teste', timezone: 'America/Sao_Paulo' }), await service().save('farms', null, { name: 'Outra operação de teste' })];
const session = { access_token: 'fixture-token', refresh_token: 'fixture-refresh', token_type: 'bearer', expires_at: Math.floor(Date.now() / 1000) + 3600, expires_in: 3600, user };
const app = express(); app.use(express.json());
let failNextWrite = false, failAfterCommit = false, incompleteAfterCommit = false, writes = 0;
const keys = [];
app.get('/api/customer/config', (_req, res) => res.json({ ok: true, supabaseUrl: 'https://auth.example.test', supabaseAnonKey: 'public-test-key' }));
app.get('/api/customer/workspace', (_req, res) => res.json({ ok: true, data: { linked: true, capabilities: { modules: true, reminders: false }, whatsappUrl: null } }));
app.get('/api/rural/farms', (_req, res) => res.json({ ok: true, data: farms }));
app.get('/api/rural/agro/catalog', (_req, res) => res.json({ ok: true, data: agroCatalog() }));
app.use('/api/rural/farms/:farmId', async (req, res, next) => {
  const domain = new RuralService(user, repo, `web:${req.get('Idempotency-Key') || randomUUID()}`);
  try {
    const farmId = req.params.farmId;
    const parts = req.path.split('/').filter(Boolean);
    let result;
    if (req.method === 'GET' && parts[0] === 'summary') result = await domain.summary(farmId);
    else if (req.method === 'GET' && parts[0] === 'activity') result = { items: [], has_more: false };
    else if (req.method === 'GET' && parts[0] === 'weather') { res.status(400).json({ ok: false, error: 'Localização não cadastrada.' }); return; }
    else if (req.method === 'GET' && parts.join('/') === 'agro/overview') result = await domain.agroOverview(farmId, ruralQuery(req.query));
    else if (req.method === 'GET' && parts.join('/') === 'expenses/summary') result = await domain.expenses(farmId, ruralQuery(req.query));
    else if (req.method === 'GET') result = parts[1] ? await domain.one(parts[0], farmId, parts[1]) : await domain.list(parts[0], farmId, ruralQuery(req.query));
    else {
      writes++; keys.push(req.get('Idempotency-Key'));
      await new Promise(resolve => setTimeout(resolve, 120));
      if (failNextWrite) { failNextWrite = false; res.status(503).json({ ok: false, error: 'Test infrastructure failure' }); return; }
      result = await domain.save(parts[0], farmId, req.body, parts[1]);
      if (failAfterCommit) { failAfterCommit = false; res.status(503).json({ ok: false, error: 'Test response lost after commit' }); return; }
      if (incompleteAfterCommit) { incompleteAfterCommit = false; res.json({ ok: true, data: {} }); return; }
    }
    res.json({ ok: true, data: result });
  } catch (error) { next(error); }
});
app.use('/app', express.static(fileURLToPath(new URL('../app/dist', import.meta.url))));
app.use(errorHandler);
const server = app.listen(0, '127.0.0.1');
await new Promise(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_CHANNEL ? { channel: process.env.BROWSER_CHANNEL } : {}) });
await mkdir('test-artifacts/agro', { recursive: true });
let checks = 0; let diagnosticPage;
try {
  for (const width of [1280, 390]) {
    const context = await browser.newContext({ viewport: { width, height: 900 }, timezoneId: 'Europe/London' });
    const page = await context.newPage(); diagnosticPage = page;
    const errors = []; page.on('pageerror', error => errors.push(error.message));
    await page.route('**/auth/v1/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(user) }));
    await page.addInitScript(({ session, id }) => { localStorage.setItem('ag-customer-auth', JSON.stringify(session)); localStorage.setItem(`ag-app-farm:${session.user.id}`, id); }, { session, id: farms[width === 1280 ? 0 : 1].id });
    await page.goto(`${base}/app/`);
    await page.getByRole('navigation').filter({ visible: true }).getByRole('button', { name: 'Fazenda', exact: true }).click();
    const workspace = page.getByRole('region', { name: 'Atividades e produção' });
    await workspace.getByRole('button', { name: 'Escolher minha atividade' }).click();
    let dialog = page.getByRole('dialog');
    await dialog.getByLabel('Tipo de atividade').selectOption('equines');
    await dialog.getByLabel('Como você chama essa atividade?').fill(`Treinamento ${width}`);
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await workspace.getByLabel('Atividade', { exact: true }).selectOption({ label: `Treinamento ${width}` });
    await workspace.getByRole('button', { name: 'Nova ficha', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Nome da ficha', { exact: true }).fill(`Luna ${width}`);
    await dialog.getByLabel('Proprietário do animal').fill('Cliente de teste');
    const beforeWrites = writes; failNextWrite = true;
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).dblclick();
    await dialog.getByRole('alert').waitFor();
    assert.equal(writes - beforeWrites, 1); checks++;
    assert.equal(await dialog.getByLabel('Nome da ficha', { exact: true }).inputValue(), `Luna ${width}`); checks++;
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await workspace.getByRole('heading', { name: `Luna ${width}`, exact: true }).waitFor();
    assert.equal(keys.at(-1), keys.at(-2)); checks++;
    await workspace.getByRole('button', { name: 'Registrar o que aconteceu' }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('O que aconteceu?').selectOption('training');
    await dialog.getByLabel('Duração (min)').fill('25');
    await dialog.getByLabel('Trabalho realizado').fill('Treino técnico de teste');
    failAfterCommit = true;
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.getByRole('alert').waitFor();
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    const events = await pg.query("select count(*) n from production_events where description='Treino técnico de teste' and farm_id=$1", [farms[width === 1280 ? 0 : 1].id]);
    assert.equal(Number(events.rows[0].n), 1); checks++;
    await workspace.getByRole('button', { name: 'Histórico', exact: true }).click();
    await workspace.getByText('Treino técnico de teste', { exact: true }).waitFor();
    await workspace.getByRole('button', { name: 'Corrigir', exact: true }).click();
    dialog = page.getByRole('dialog'); await dialog.getByLabel('Duração (min)').fill('30');
    await dialog.getByRole('button', { name: 'Salvar correção' }).click();
    await workspace.getByText('30 min', { exact: true }).waitFor(); checks++;
    await workspace.getByRole('button', { name: 'Vendas e recebimentos' }).click();
    await workspace.getByRole('button', { name: 'Nova venda ou serviço' }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Produto ou serviço').fill('Treinamento mensal');
    await dialog.getByLabel('Cliente', { exact: true }).fill('Cliente do CT');
    await dialog.getByLabel('Valor total (R$)').fill('500');
    await dialog.getByLabel('Vencimento', { exact: true }).fill('2026-12-01');
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await workspace.getByText('Treinamento mensal', { exact: true }).waitFor();
    await workspace.getByRole('button', { name: 'Receber', exact: true }).click();
    dialog = page.getByRole('dialog'); await dialog.getByLabel('Valor recebido (R$)').fill('200');
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await workspace.getByText(/a receber R\$\s*300,00/).waitFor(); checks++;
    await workspace.getByRole('button', { name: 'Ver recebimentos' }).click();
    await workspace.getByRole('region', { name: 'Recebimentos da venda' }).getByText(/200,00/).waitFor(); checks++;
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: `test-artifacts/agro/finance-${width}.png`, fullPage: true });
    await workspace.getByRole('button', { name: 'Fichas', exact: true }).click();
    await workspace.getByRole('button', { name: 'Abrir ficha' }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Proprietário do animal').fill('');
    await dialog.getByRole('button', { name: 'Salvar correção' }).click();
    await dialog.waitFor({state:'detached'});
    const units = await pg.query('select owner_name from production_units where name=$1', [`Luna ${width}`]);
    assert.equal(units.rows[0].owner_name, null); checks++;
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: `test-artifacts/agro/units-${width}.png`, fullPage: true });
    await workspace.getByRole('button', { name: 'Agendar tarefa', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('O que precisa ser feito?').fill(`Ferrageamento ${width}`);
    await dialog.getByLabel('Dia e horário (America/Sao_Paulo)').fill('2099-10-02T09:00');
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    let task = (await pg.query('select * from farm_tasks where title=$1', [`Ferrageamento ${width}`])).rows[0];
    assert.equal(new Date(task.due_at).toISOString(), '2099-10-02T12:00:00.000Z'); checks++;
    assert.ok(task.production_unit_id); checks++;
    await workspace.getByRole('button', { name: 'Agenda', exact: true }).click();
    await workspace.getByRole('button', { name: 'Editar tarefa' }).click();
    dialog = page.getByRole('dialog');
    assert.equal(await dialog.getByLabel('Dia e horário (America/Sao_Paulo)').inputValue(), '2099-10-02T09:00'); checks++;
    await dialog.getByLabel('Dia e horário (America/Sao_Paulo)').fill('2099-10-03T11:00');
    await dialog.getByRole('button', { name: 'Salvar correção', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    task = (await pg.query('select * from farm_tasks where id=$1', [task.id])).rows[0];
    assert.equal(new Date(task.due_at).toISOString(), '2099-10-03T14:00:00.000Z'); checks++;
    await workspace.getByRole('button', { name: 'Adicionar atividade', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Tipo de atividade').selectOption('dairy_cattle');
    await dialog.getByLabel('Como você chama essa atividade?').fill(`Leite ${width}`);
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    await workspace.getByRole('button', { name: 'Fichas', exact: true }).click();
    await workspace.getByRole('button', { name: 'Nova ficha', exact: true }).click();
    dialog = page.getByRole('dialog'); await dialog.getByLabel('Nome da ficha', { exact: true }).fill(`Vaca ${width}`);
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await workspace.getByRole('heading', { name: `Vaca ${width}`, exact: true }).waitFor();
    await workspace.getByRole('button', { name: 'Registrar o que aconteceu' }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('O que aconteceu?').selectOption('milk');
    await dialog.getByLabel('Leite produzido (L)').fill('12.5');
    await dialog.getByLabel(/^Período/).selectOption('morning');
    incompleteAfterCommit = true;
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.getByRole('alert').filter({ hasText: 'confirmação chegou incompleta' }).waitFor(); checks++;
    await dialog.getByRole('button', { name: 'Salvar registro', exact: true }).click();
    await dialog.waitFor({ state: 'detached' });
    assert.equal(keys.at(-1), keys.at(-2)); checks++;
    await workspace.getByRole('button', { name: 'Histórico', exact: true }).click();
    await workspace.getByText(/12,5 L/).first().waitFor();
    const milk = (await pg.query("select * from production_events where event_type='milk' and farm_id=$1", [farms[width === 1280 ? 0 : 1].id])).rows[0];
    assert.equal(milk.unit, 'L'); assert.equal(Number(milk.quantity), 12.5); checks += 2;
    assert.equal(await workspace.getByText('Treino técnico de teste', { exact: true }).count(), 0); checks++;
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.screenshot({ path: `test-artifacts/agro/milk-${width}.png`, fullPage: true });
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
    assert.equal(overflow, false); assert.deepEqual(errors, []); checks += 2;
    await context.close();
  }
  console.log(`Agro UI: ${checks} verificações em desktop e mobile, com PostgreSQL local e sem chamadas pagas.`);
} catch(error) { if(diagnosticPage) { await diagnosticPage.screenshot({path:'test-artifacts/agro/failure.png',fullPage:true}).catch(()=>{}); console.log((await diagnosticPage.locator('body').innerText()).slice(-3500)); } throw error; } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); await pg.close(); }
